api = "0.10"

[buildpack]
  description = "A Cloud Native Buildpack with an order definition suitable for solc applications"
  homepage = "https://github.com/amp-buildpacks/solc"
  id = "amp-buildpacks/solc"
  keywords = ["solc", "composite"]
  name = "Solc Build Pack"
  version = "0.0.1"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/amp-buildpacks/solc/blob/main/LICENSE"

# Targets the buildpack will work with
[[targets]]
os = "linux"

# Stacks (deprecated) the buildpack will work with
[[stacks]]
  id = "io.buildpacks.samples.stacks.jammy"
